name: CI

on:
  pull_request:
  push:
    branches: [main, master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check, lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: rustup component add clippy rustfmt

      - uses: Swatinem/rust-cache@v2

      # - name: Format
      #   run: cargo fmt --all --check

      # - name: Clippy
      #   run: cargo clippy --all-targets

      - name: Build
        run: cargo build
