name: Demo

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
        cache-dependency-path: demo/package-lock.json
    # For some reason installing the rust toolchain via wasm-pack leads to CI failures.
    # This will read the top level rustup-toolchain.toml and install the required stuff.
    - name: Trigger toolchain installation
      working-directory: ./demo
      run: cargo fetch --locked
    - name: Build demo
      working-directory: ./demo
      run: |
        npm ci
        npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.6.8
      with:
        folder: demo/dist
        branch: gh-pages
